# Generated by Django 5.1.15 on 2026-09-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GISLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_id', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('layer_type', models.CharField(choices=[('VECTOR_POLYGON', 'Vector Polygon'), ('VECTOR_LINE', 'Vector Line'), ('VECTOR_POINT', 'Vector Point'), ('VOLUME_3D', '3D Volumetric Extrusions'), ('RASTER_TERRAIN', 'DEM / Raster Terrain'), ('AI_EXTRACTED', 'AI Extracted Features')], default='VECTOR_POLYGON', max_length=32)),
                ('is_visible', models.BooleanField(default=True)),
                ('opacity', models.FloatField(default=1.0)),
                ('color_hex', models.CharField(default='#38bdf8', max_length=16)),
                ('style_json', models.JSONField(blank=True, null=True)),
                ('geojson_data', models.JSONField(blank=True, null=True)),
                ('feature_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
