# Generated by Django 5.1.15 on 2026-09-05 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('floors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(db_index=True, max_length=32)),
                ('property_type', models.CharField(choices=[('APARTMENT', 'Apartment'), ('OFFICE', 'Commercial Office'), ('SHOP', 'Retail Shop'), ('PARKING', 'Underground/Covered Parking'), ('UTILITY', 'Utility / Plant Room'), ('INFRASTRUCTURE', 'Subsurface Infrastructure'), ('AIR_RIGHT', 'Air Right'), ('OTHER', 'Other')], default='APARTMENT', max_length=32)),
                ('owner_name', models.CharField(default='Public Allotment', max_length=128)),
                ('owner_id_hash', models.CharField(blank=True, default='', max_length=64)),
                ('area', models.FloatField(help_text='Carpet/Built area in square meters')),
                ('x_min', models.FloatField(blank=True, help_text='Metric offset Xmin', null=True)),
                ('x_max', models.FloatField(blank=True, help_text='Metric offset Xmax', null=True)),
                ('y_min', models.FloatField(blank=True, help_text='Metric offset Ymin', null=True)),
                ('y_max', models.FloatField(blank=True, help_text='Metric offset Ymax', null=True)),
                ('z_min', models.FloatField(help_text='Bottom elevation (Zmin) in meters')),
                ('z_max', models.FloatField(help_text='Top elevation (Zmax) in meters')),
                ('volume', models.FloatField(blank=True, help_text='3D Volume in cubic meters', null=True)),
                ('geometry', models.JSONField(help_text='GeoJSON 2D boundary polygon coordinates')),
                ('geometry_3d', models.JSONField(blank=True, help_text='GeoJSON 3D coordinates or volumetric prism', null=True)),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered & Verified'), ('PROVISIONAL', 'Provisional Draft'), ('CONFLICT_FLAGGED', 'Conflict Flagged'), ('DISPUTED', 'Disputed Ownership')], default='REGISTERED', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='floors.floor')),
            ],
            options={
                'ordering': ['floor__floor_number', 'unit_number'],
                'unique_together': {('floor', 'unit_number')},
            },
        ),
    ]
