# Generated by Django 5.1.15 on 2026-09-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('INFO', 'Informational'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical Violation')], default='ERROR', max_length=16)),
                ('issue_type', models.CharField(choices=[('VERTICAL_OVERLAP', '3D Vertical Overlap Detected'), ('HORIZONTAL_OVERLAP', '2D Spatial Encroachment'), ('VOLUMETRIC_COLLISION', 'Full 3D Volumetric Collision'), ('OUTSIDE_PARCEL', 'Property/Building Outside Parcel Boundary'), ('FLOOR_GAP', 'Unregistered Floor Gap'), ('INVALID_Z_RANGE', 'Invalid Z-Range (Zmin >= Zmax)'), ('DUPLICATE_ULPIN', 'Duplicate 3D ULPIN Conflict'), ('INFRASTRUCTURE_COLLISION', 'Underground Utility Collision'), ('GEOMETRY_INVALID', 'Invalid Geometric Topology')], default='VERTICAL_OVERLAP', max_length=32)),
                ('message', models.TextField()),
                ('affected_objects', models.JSONField(help_text='List of identifiers or ULPINs involved e.g. ["503", "504"]')),
                ('location', models.JSONField(blank=True, help_text='GeoJSON Point or Polygon of conflict', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active / Unresolved'), ('ACKNOWLEDGED', 'Acknowledged by Surveyor'), ('RESOLVED', 'Resolved / Rectified'), ('IGNORED', 'Permitted Deviation')], default='ACTIVE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
