# Generated by Django 5.1.15 on 2026-09-05 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.IntegerField(help_text='Negative for basements, 0 for ground, positive for upper floors')),
                ('floor_label', models.CharField(help_text='Display name e.g. Basement -2, Ground, Floor 5', max_length=64)),
                ('level_code', models.CharField(help_text='Standardized level code e.g. B02, B01, G00, F05', max_length=16)),
                ('z_min', models.FloatField(help_text='Bottom elevation in meters relative to ground')),
                ('z_max', models.FloatField(help_text='Top elevation in meters relative to ground')),
                ('floor_height', models.FloatField(help_text='Net vertical height of the floor in meters')),
                ('geometry', models.JSONField(blank=True, help_text='GeoJSON 2D floor boundary polygon', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='buildings.building')),
            ],
            options={
                'ordering': ['building', 'floor_number'],
                'unique_together': {('building', 'floor_number')},
            },
        ),
    ]
