# Generated by Django 5.1.15 on 2026-09-05 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ULPINRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ulpin_code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('state_code', models.CharField(default='UT', max_length=8)),
                ('district_code', models.CharField(default='HW', max_length=8)),
                ('parcel_code', models.CharField(max_length=32)),
                ('building_code', models.CharField(max_length=32)),
                ('level_code', models.CharField(max_length=16)),
                ('unit_code', models.CharField(max_length=16)),
                ('is_valid', models.BooleanField(default=True)),
                ('disclaimer', models.CharField(default='Prototype 3D ULPIN / Demonstration Identifier (Research Model)', max_length=256)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ulpin_record', to='properties.propertyunit')),
            ],
            options={
                'ordering': ['ulpin_code'],
            },
        ),
    ]
