# Generated by Django 5.1.15 on 2026-09-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('surveyor_name', models.CharField(default='Authorized Surveyor', max_length=128)),
                ('survey_format', models.CharField(choices=[('GEOJSON', 'GeoJSON Vector Layer'), ('CSV', 'CSV Point / Boundary Table'), ('KML', 'KML / KMZ Spatial File'), ('LAS_LAZ', 'LiDAR LAS / LAZ Point Cloud'), ('DRONE_IMAGE', 'Drone Orthomosaic Imagery')], default='GEOJSON', max_length=32)),
                ('file', models.FileField(blank=True, null=True, upload_to='surveys/')),
                ('raw_content', models.TextField(blank=True, default='', help_text='Raw text or JSON snippet')),
                ('parsed_features_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Processing'), ('PROCESSED', 'Processed & Converted'), ('VERIFIED', 'Field Survey Verified'), ('REJECTED', 'Rejected (Geometry Invalid)')], default='PROCESSED', max_length=32)),
                ('survey_metadata', models.JSONField(blank=True, help_text='CRS, accuracy, CORS reference, elevation datum', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
