# Generated by Django 5.1.15 on 2026-09-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_number', models.CharField(db_index=True, max_length=64, unique=True)),
                ('state', models.CharField(default='Uttarakhand', max_length=64)),
                ('state_code', models.CharField(default='UT', max_length=8)),
                ('district', models.CharField(default='Haridwar', max_length=64)),
                ('district_code', models.CharField(default='HW', max_length=8)),
                ('tehsil', models.CharField(default='Haridwar', max_length=64)),
                ('village', models.CharField(default='Shivalik Nagar', max_length=64)),
                ('area', models.FloatField(help_text='Area in square meters')),
                ('ground_elevation', models.FloatField(default=280.0, help_text='Ground elevation in meters MSL')),
                ('geometry', models.JSONField(help_text='GeoJSON Polygon footprint coordinates [[lon, lat], ...]')),
                ('centroid', models.JSONField(blank=True, help_text='GeoJSON Point [lon, lat]', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['parcel_number'],
            },
        ),
    ]
