# Generated by Django 5.1.15 on 2026-09-05 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('asset_type', models.CharField(choices=[('WATER_SUPPLY', 'Potable Water Pipeline'), ('SEWERAGE', 'Sewer / Storm Drainage'), ('ELECTRICITY', 'High-Voltage Power Duct'), ('METRO_TUNNEL', 'Subway / Metro Tunnel'), ('GAS_PIPELINE', 'Natural Gas Pipeline'), ('TELECOM', 'Fiber Optic Telecom Duct')], default='WATER_SUPPLY', max_length=32)),
                ('depth_min', models.FloatField(help_text='Top depth in meters (negative Z or distance below ground e.g. -2.0)')),
                ('depth_max', models.FloatField(help_text='Bottom depth in meters (negative Z e.g. -4.5)')),
                ('diameter_m', models.FloatField(default=0.5, help_text='Diameter/thickness in meters')),
                ('geometry', models.JSONField(help_text='GeoJSON LineString or Polygon coordinates')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active & Operational'), ('MAINTENANCE', 'Under Maintenance'), ('PLANNED', 'Proposed / Planned'), ('DECOMMISSIONED', 'Decommissioned')], default='ACTIVE', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infrastructure_assets', to='parcels.parcel')),
            ],
            options={
                'ordering': ['depth_min', 'asset_id'],
            },
        ),
    ]
