# Generated by Django 5.1.15 on 2026-09-05 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_code', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('building_type', models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial'), ('MIXED_USE', 'Mixed Use'), ('INSTITUTIONAL', 'Institutional'), ('INDUSTRIAL', 'Industrial')], default='MIXED_USE', max_length=32)),
                ('number_of_floors', models.IntegerField(default=6)),
                ('number_of_basements', models.IntegerField(default=2)),
                ('height', models.FloatField(help_text='Building height in meters above ground')),
                ('ground_elevation', models.FloatField(default=280.0, help_text='Base ground elevation in meters MSL')),
                ('geometry_2d', models.JSONField(help_text='GeoJSON footprint polygon coordinates')),
                ('geometry_3d', models.JSONField(blank=True, help_text='GeoJSON 3D coordinates or bounding specs', null=True)),
                ('source', models.CharField(choices=[('SURVEY', 'Field Survey'), ('DRONE', 'Drone Photogrammetry'), ('LIDAR', 'LiDAR Point Cloud'), ('AI_EXTRACTED', 'AI Extraction')], default='SURVEY', max_length=32)),
                ('confidence_score', models.FloatField(default=1.0, help_text='0.0 to 1.0 confidence score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='parcels.parcel')),
            ],
            options={
                'ordering': ['building_code'],
                'unique_together': {('parcel', 'building_code')},
            },
        ),
    ]
